{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-fakefilesystem/3.11.0/okio-fakefilesystem-3.11.0.module",
    "group": "com.squareup.okio",
    "module": "okio-fakefilesystem",
    "version": "3.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-fakefilesystem-jvm-3.11.0.jar",
          "url": "okio-fakefilesystem-jvm-3.11.0.jar",
          "size": 25773,
          "sha512": "ce62e95bfb5314deae62e9a0a1c68c3353bfc6725785f2a8b3140b1663e56257229c9b879ba382744b907655a6417be653012e50e172917fff4572067d322572",
          "sha256": "3dc4343f7c2b26ddc8c096bbe1962948eb3a8ca46e7683ce494a56561e66c7fd",
          "sha1": "48b69ddeda906b81556c405e9c498f5488712c76",
          "md5": "d64e9d460034f023bfb5bc59fbcb7df4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-fakefilesystem-jvm-3.11.0.jar",
          "url": "okio-fakefilesystem-jvm-3.11.0.jar",
          "size": 25773,
          "sha512": "ce62e95bfb5314deae62e9a0a1c68c3353bfc6725785f2a8b3140b1663e56257229c9b879ba382744b907655a6417be653012e50e172917fff4572067d322572",
          "sha256": "3dc4343f7c2b26ddc8c096bbe1962948eb3a8ca46e7683ce494a56561e66c7fd",
          "sha1": "48b69ddeda906b81556c405e9c498f5488712c76",
          "md5": "d64e9d460034f023bfb5bc59fbcb7df4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "okio-fakefilesystem-jvm-3.11.0-sources.jar",
          "url": "okio-fakefilesystem-jvm-3.11.0-sources.jar",
          "size": 8413,
          "sha512": "cb4fb94a52c905aaa9ad083dae916532bca1d90e410a736c8cd0dfcf277a4508bb05c4f790a844e8f937c18d19853c4dc7adb967e18cb0d3ff97756bd84f41a5",
          "sha256": "72b36ee3c7267a6cd7373d639a3ae680f2cca2e1f93b23562f437941e6acfa94",
          "sha1": "25aaa8508f23399f7ee242c6c2a9be1ec32711a5",
          "md5": "81cea84046945f3088b910c115edef1e"
        }
      ]
    }
  ]
}
