{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.7/kotlin-logging-7.0.7.module",
    "group": "io.github.oshai",
    "module": "kotlin-logging",
    "version": "7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-jvm-7.0.7.jar",
          "url": "kotlin-logging-jvm-7.0.7.jar",
          "size": 109019,
          "sha512": "2e1c7ec74e075374d1356d9124c5c7a7c6e76e67f210940645e02b1157f94ac1b044a173716b1c221be9fabc349dfba67f8c99ff70b6e611a992d1b64794031b",
          "sha256": "c373f7f4c9efc85c4f70f11519f2a1b7878bc0ed75a325364d034af3fa21f776",
          "sha1": "59500693668b6c70e9580c651298734054d20284",
          "md5": "f21ef7890426b999bfd584a9e5fe417e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-jvm-7.0.7.jar",
          "url": "kotlin-logging-jvm-7.0.7.jar",
          "size": 109019,
          "sha512": "2e1c7ec74e075374d1356d9124c5c7a7c6e76e67f210940645e02b1157f94ac1b044a173716b1c221be9fabc349dfba67f8c99ff70b6e611a992d1b64794031b",
          "sha256": "c373f7f4c9efc85c4f70f11519f2a1b7878bc0ed75a325364d034af3fa21f776",
          "sha1": "59500693668b6c70e9580c651298734054d20284",
          "md5": "f21ef7890426b999bfd584a9e5fe417e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-logging-jvm-7.0.7-sources.jar",
          "url": "kotlin-logging-jvm-7.0.7-sources.jar",
          "size": 30413,
          "sha512": "24a009b00ae11f7053272043facb8c3a0cef22a74fbae3a4dabf86e85f12d107f06d34f5f52f50a20132070dcf5ac11c9491a842c16b5b5bb99a21b47042c043",
          "sha256": "e91e9f9b65ac4c4a98e6041421a640ea164eda17a516fce1d10684240dd76a74",
          "sha1": "bb7babc66362bd13b5a671965c3184b9e6f37826",
          "md5": "a541135bedd4da467268e4714035fb07"
        }
      ]
    }
  ]
}
