{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio/3.11.0/okio-3.11.0.module",
    "group": "com.squareup.okio",
    "module": "okio",
    "version": "3.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-iosArm64Main-3.11.0.klib",
          "url": "okio-iosarm64-3.11.0.klib",
          "size": 479707,
          "sha512": "e5bfba964bcf378edb4845ac2a6b5e43a96036f511d4cdaf27f17579b8a103f6a6486292f4afa4f37b16ce24f8de46eb809dcddf84c2b9f942c5caf564d82d08",
          "sha256": "3a76333eeab52a75d83f098a685a86f21160ccae3647f2d1cb7d1b920ba7ffc0",
          "sha1": "1af854805bb961d301664e9c92c273c46679d1f4",
          "md5": "b4a82280987d9b267aded7ba973b3636"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "okio-iosarm64-3.11.0-sources.jar",
          "url": "okio-iosarm64-3.11.0-sources.jar",
          "size": 169949,
          "sha512": "646c9e88dc3e566f14d5700c4cb592c27c6dca36bc4c12a41132e2e304ff5683f760c576b60b48b635c5240bdfa38011ff7158ff36ecbb8120214f6a86b5f2a9",
          "sha256": "3eb1009aad4a5f689e636f49b1d6c82f58b8bba21a43eaa2502f1fc8878fa506",
          "sha1": "b9489cd3c0975674dab99816c412ab52a032c2e2",
          "md5": "a229a862405b385712bcefe48daa8504"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-iosarm64-3.11.0-metadata.jar",
          "url": "okio-iosarm64-3.11.0-metadata.jar",
          "size": 4585,
          "sha512": "a22a229de81b808234b18f1cc476c3f6f44bdf28aa47223d1e7640f3c27a94ef6b8f71281100a8e6fd4b5450b6775c4e205e7a28db8e8b869b359cb1a340974d",
          "sha256": "dd5dd38044ce63cbff5c0a5cbfc94bbf809b8eeb0999f5112b39ffe755a74c09",
          "sha1": "22dc4b428b54f1ef996fb35d43aff7a876239f61",
          "md5": "60f0c2dff3acfb6687e83facd225d691"
        }
      ]
    }
  ]
}
