{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bignum/0.3.10/bignum-0.3.10.module",
    "group": "com.ionspin.kotlin",
    "module": "bignum",
    "version": "0.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "bignum.klib",
          "url": "bignum-iosx64-0.3.10.klib",
          "size": 440177,
          "sha512": "448e6653e98fb172014bdc589e7014e2afa1140aa88d30b4b8080ff55863971e7afdc1f665a523e94a319be15ab360c8a066313435484f22b6e31527856c1fbf",
          "sha256": "ad6bd0387ea6748fabc54c2dedfb4ec9fdcf18c9a56bc2730acd0d78e34297e8",
          "sha1": "5a251c8a922f3829c9972daa9ac88b2b9464e217",
          "md5": "d21f97b231da8e2790179f90f99a2178"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "bignum-iosx64-0.3.10-sources.jar",
          "url": "bignum-iosx64-0.3.10-sources.jar",
          "size": 90858,
          "sha512": "e1b7b37d25212e7c6cb48640ff38c3fa71c3dedcc425ab8fbbc3e9128d8ccd8efc24d8379da083516267fd7dfcb8e11e001a87cff4657318b3eee7701a43782e",
          "sha256": "43282ee1aaef090aa2721c8cbabef2c4281afb60ff0df481a5ad509ce9ca6630",
          "sha1": "39f081a4a13bff8a7f65b8735b600e83a027c651",
          "md5": "59ee189ee079613da30d9a5e46f064aa"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "bignum-iosx64-0.3.10-metadata.jar",
          "url": "bignum-iosx64-0.3.10-metadata.jar",
          "size": 2854,
          "sha512": "d27e42f3f7de4b0bcebb605082b8b1792b1d32d7bf947aff6f680e9a8728d9a812da06ae93e622a1ccbb960bd2e0a600ffd11124368d90041c6ce21c9a3ea201",
          "sha256": "e505dc5fde88c6d8938b46fc7b65c9aba3e1d249b7cf9b302b11e797cdf0f56e",
          "sha1": "09f7126b150a08340ae161989ce5049a26dbdfe9",
          "md5": "d0b46b14746318dcb777f3936bf5f44f"
        }
      ]
    }
  ]
}
