{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-test/1.10.2/kotlinx-coroutines-test-1.10.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-test",
    "version": "1.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-iosSimulatorArm64Main-1.10.2.klib",
          "url": "kotlinx-coroutines-test-iossimulatorarm64-1.10.2.klib",
          "size": 78398,
          "sha512": "8f5f3e374fc705b04d977c3ca19e66b5b603ee401f86f16c061974bc58bd03cba566de0259320e93951da55805f63e4026dc4cad2d3d3b19523eee2d1550baed",
          "sha256": "81256c4b5b68090f8a3c49ceb566ea94d6070600746e3d7a956c3010c433dabf",
          "sha1": "5504c6abb4e8789307fe6fd7022cf6e8d0f6d7da",
          "md5": "568d5dec5bede67224f955313b3be38e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-test-iossimulatorarm64-1.10.2-sources.jar",
          "url": "kotlinx-coroutines-test-iossimulatorarm64-1.10.2-sources.jar",
          "size": 25551,
          "sha512": "0b86541175c8bc10d764f2f4d295f4f92ca688ea46140a7bfc2df9b0118c70ca873915cd172b1b22aef84f5be8aa7b3c5595a554925a0ecfc6bfaf11347ccb9d",
          "sha256": "1bd49665fd31fc15b841b13b70fca8820afb4f90c87043904e879dc1a80a3b0d",
          "sha1": "70fde0188fb0a9d5d20929d348a22714d8389e19",
          "md5": "afe9605896140cd48b74065440ca89fd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-iossimulatorarm64-1.10.2-metadata.jar",
          "url": "kotlinx-coroutines-test-iossimulatorarm64-1.10.2-metadata.jar",
          "size": 261,
          "sha512": "360035da0253862bcb775b32f3d120dfc4ba5472ab7b10d9dd4e380de68d2a8eadb0b21dceb801f96c2232c6ba17782f688432fc9132f0f1217860307cfda14c",
          "sha256": "a5357dbcae1319b9cb97d330f6471ac74ce0e7da3adc470683d1666af18300a9",
          "sha1": "661ac3858023c7636af49d989cccb45bfaf86046",
          "md5": "6a9eab4259b82c480558177478b8391e"
        }
      ]
    }
  ]
}
