{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okio",
    "module": "okio-fakefilesystem",
    "version": "3.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-fakefilesystem-metadata-3.11.0.jar",
          "url": "okio-fakefilesystem-3.11.0.jar",
          "size": 4660,
          "sha512": "d6d633f20045a1788690e01139bd0e7aa17e540b0a7c52931510666bc2b5013be13db6916fb89506ec550b51727a7bdd2afdbebc71a1071c1a09f7e7317c00de",
          "sha256": "48297c9395aea9cf4a8d303629da25fe917879590d8cefcd59eee5459ab14449",
          "sha1": "5cb2a01951ece96b12ae7fd8b274a5bacc97ba14",
          "md5": "839ecd5d4edc51e83643ef42ea456d8d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "okio-fakefilesystem-kotlin-3.11.0-sources.jar",
          "url": "okio-fakefilesystem-3.11.0-sources.jar",
          "size": 8413,
          "sha512": "cb4fb94a52c905aaa9ad083dae916532bca1d90e410a736c8cd0dfcf277a4508bb05c4f790a844e8f937c18d19853c4dc7adb967e18cb0d3ff97756bd84f41a5",
          "sha256": "72b36ee3c7267a6cd7373d639a3ae680f2cca2e1f93b23562f437941e6acfa94",
          "sha1": "25aaa8508f23399f7ee242c6c2a9be1ec32711a5",
          "md5": "81cea84046945f3088b910c115edef1e"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iosarm64/3.11.0/okio-fakefilesystem-iosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iosarm64/3.11.0/okio-fakefilesystem-iosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iosarm64/3.11.0/okio-fakefilesystem-iosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iossimulatorarm64/3.11.0/okio-fakefilesystem-iossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iossimulatorarm64/3.11.0/okio-fakefilesystem-iossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iossimulatorarm64/3.11.0/okio-fakefilesystem-iossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iosx64/3.11.0/okio-fakefilesystem-iosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iosx64/3.11.0/okio-fakefilesystem-iosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-iosx64/3.11.0/okio-fakefilesystem-iosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-iosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-js/3.11.0/okio-fakefilesystem-js-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-js",
        "version": "3.11.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-js/3.11.0/okio-fakefilesystem-js-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-js",
        "version": "3.11.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-js/3.11.0/okio-fakefilesystem-js-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-js",
        "version": "3.11.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-jvm/3.11.0/okio-fakefilesystem-jvm-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-jvm",
        "version": "3.11.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-jvm/3.11.0/okio-fakefilesystem-jvm-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-jvm",
        "version": "3.11.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-jvm/3.11.0/okio-fakefilesystem-jvm-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-jvm",
        "version": "3.11.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-linuxarm64/3.11.0/okio-fakefilesystem-linuxarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-linuxarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-linuxarm64/3.11.0/okio-fakefilesystem-linuxarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-linuxarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-linuxx64/3.11.0/okio-fakefilesystem-linuxx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-linuxx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-linuxx64/3.11.0/okio-fakefilesystem-linuxx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-linuxx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-macosarm64/3.11.0/okio-fakefilesystem-macosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-macosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-macosarm64/3.11.0/okio-fakefilesystem-macosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-macosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-macosarm64/3.11.0/okio-fakefilesystem-macosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-macosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-macosx64/3.11.0/okio-fakefilesystem-macosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-macosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-macosx64/3.11.0/okio-fakefilesystem-macosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-macosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-macosx64/3.11.0/okio-fakefilesystem-macosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-macosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-mingwx64/3.11.0/okio-fakefilesystem-mingwx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-mingwx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-mingwx64/3.11.0/okio-fakefilesystem-mingwx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-mingwx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvosarm64/3.11.0/okio-fakefilesystem-tvosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvosarm64/3.11.0/okio-fakefilesystem-tvosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvosarm64/3.11.0/okio-fakefilesystem-tvosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvossimulatorarm64/3.11.0/okio-fakefilesystem-tvossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvossimulatorarm64/3.11.0/okio-fakefilesystem-tvossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvossimulatorarm64/3.11.0/okio-fakefilesystem-tvossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvosx64/3.11.0/okio-fakefilesystem-tvosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvosx64/3.11.0/okio-fakefilesystem-tvosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-tvosx64/3.11.0/okio-fakefilesystem-tvosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-tvosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-wasm-js/3.11.0/okio-fakefilesystem-wasm-js-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-wasm-js",
        "version": "3.11.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-wasm-js/3.11.0/okio-fakefilesystem-wasm-js-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-wasm-js",
        "version": "3.11.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-wasm-js/3.11.0/okio-fakefilesystem-wasm-js-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-wasm-js",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosarm32/3.11.0/okio-fakefilesystem-watchosarm32-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosarm32",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosarm32/3.11.0/okio-fakefilesystem-watchosarm32-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosarm32",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosarm32/3.11.0/okio-fakefilesystem-watchosarm32-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosarm32",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosarm64/3.11.0/okio-fakefilesystem-watchosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosarm64/3.11.0/okio-fakefilesystem-watchosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosarm64/3.11.0/okio-fakefilesystem-watchosarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosdevicearm64/3.11.0/okio-fakefilesystem-watchosdevicearm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosdevicearm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosdevicearm64/3.11.0/okio-fakefilesystem-watchosdevicearm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosdevicearm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosdevicearm64/3.11.0/okio-fakefilesystem-watchosdevicearm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosdevicearm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchossimulatorarm64/3.11.0/okio-fakefilesystem-watchossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchossimulatorarm64/3.11.0/okio-fakefilesystem-watchossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchossimulatorarm64/3.11.0/okio-fakefilesystem-watchossimulatorarm64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchossimulatorarm64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosx64/3.11.0/okio-fakefilesystem-watchosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosx64/3.11.0/okio-fakefilesystem-watchosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosx64",
        "version": "3.11.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-watchosx64/3.11.0/okio-fakefilesystem-watchosx64-3.11.0.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-watchosx64",
        "version": "3.11.0"
      }
    }
  ]
}
