{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.7/kotlin-logging-7.0.7.module",
    "group": "io.github.oshai",
    "module": "kotlin-logging",
    "version": "7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-iosX64Main-7.0.7.klib",
          "url": "kotlin-logging-iosx64-7.0.7.klib",
          "size": 51650,
          "sha512": "312447a6e45748e6e0f1cddd6fa6413c03336848e2a806853343a2714b38c8ebd4c39577a263fe8173c6e01fd7de662449140893ab9ee4d40525304ec75d7734",
          "sha256": "602362d90d0fc2a861843b0abc26c5806a06841d0212e2ae38bba5ee77694608",
          "sha1": "9e4726dedde6fe45965a6d929a16f61f38271b54",
          "md5": "cd0e1fb2f3283e4b76cb48288e5026e2"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-logging-iosx64-7.0.7-sources.jar",
          "url": "kotlin-logging-iosx64-7.0.7-sources.jar",
          "size": 16496,
          "sha512": "bd1dab8709b1a2d3cc798bf285bf936216e5ea5759f80e89e8af56bcf76e52d30352deaf335e0dc0fe8bb230482e02b022c7c872377418038668a3f372015996",
          "sha256": "4e273ad46eff6f1878a64f6b6ff98477709223dfecaa6d63fd3019fbb4da6162",
          "sha1": "2bfe758ad68d35ee3131001cd5dff984e52c890b",
          "md5": "50ce16cbbf7a625e8b862c29d87b3b79"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-iosx64-7.0.7-metadata.jar",
          "url": "kotlin-logging-iosx64-7.0.7-metadata.jar",
          "size": 9231,
          "sha512": "3e24d189e9263af707979cdc81b30c9770851716abd865b4f3f66fca3550cd2a72dcade500cea9b4da915280019705092a4d64c1886aaae6fb014e6ec30905ee",
          "sha256": "25349f2007d1a4372f0e413503ff63ff03eadc7d86d866f4cdecba1ebb36754e",
          "sha1": "70502520da3687ee05842f57528459e87a2ec54d",
          "md5": "4c254bb8de804fa15bd7472b074713b0"
        }
      ]
    }
  ]
}
