{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.2/kotlinx-serialization-core-1.6.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-iosx64-1.6.2.klib",
          "size": 305940,
          "sha512": "d51a9533c13db0711308f5e36ea46cd7ac4ef5c3a850089966e2f761a0ddd8252b23b848f0bbf3bbd9d68de4c06711461780dde89e67b7ab1411ff3bfadd6fd4",
          "sha256": "73411e8a5be3b4ac9e8ff5e775a291cfc75a3c90e84f315a808d8cd8e9df48d7",
          "sha1": "271faec9e011bdca529a3ac593660164249e60a3",
          "md5": "7b9f1276e9453fb6ae2472e6873e423b"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-iosx64-1.6.2-sources.jar",
          "url": "kotlinx-serialization-core-iosx64-1.6.2-sources.jar",
          "size": 98857,
          "sha512": "163610cc58e56be22e56b67fb0e0c535bcdd3dde4f0cd6473749e44e3289e77e18ab6292bf29d514092a2b9c44f5105b03fc0dc4c32dfc1bb5e31f30a241f05f",
          "sha256": "3e4d8b02762c2c4843cdd45c201ec15b185e2782b52725084b1a5af308c95a0e",
          "sha1": "8e0e1f18ea762eae25a212bad83d20a3b7ae7035",
          "md5": "131fdce0948b4b0a66ea3dfc883b695e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-iosx64-1.6.2-metadata.jar",
          "url": "kotlinx-serialization-core-iosx64-1.6.2-metadata.jar",
          "size": 261,
          "sha512": "b7ffcb13a7752eeaaef926ca48a81d532670ba309056288a07fe1e3476ee36e27e725118f733f4961d1e40255f787d35599f44b122a0388fd9ca22032bf81482",
          "sha256": "6ded067663779f83b813ed8a8742e1132aa82ede699709450519346955af9420",
          "sha1": "c2171f605898e5256530af436fd652ce85bbe12c",
          "md5": "8b40809965acb6fdac3a1dd13edf0224"
        }
      ]
    }
  ]
}
