{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.1.21/kotlin-test-2.1.21.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.1.21.jar",
          "url": "kotlin-test-junit-2.1.21.jar",
          "size": 5075,
          "sha512": "4808932e02ef42ec04a6b97953730c6a0b135a35619a54596a594c189e9eee172075c2b00bf2295475173c58e8b11b4ae08ecad47866f8ca1143f9f08401a4d8",
          "sha256": "45ca97f27b3ed86ce5b77473962da539cef652f5fe5414524e79b863d83ce867",
          "sha1": "d33ba2a34257b7ffb5a8c9c593704b177c7ef7be",
          "md5": "053aa962c1074510b3fb7d273f4409d1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.1.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.1.21.jar",
          "url": "kotlin-test-junit-2.1.21.jar",
          "size": 5075,
          "sha512": "4808932e02ef42ec04a6b97953730c6a0b135a35619a54596a594c189e9eee172075c2b00bf2295475173c58e8b11b4ae08ecad47866f8ca1143f9f08401a4d8",
          "sha256": "45ca97f27b3ed86ce5b77473962da539cef652f5fe5414524e79b863d83ce867",
          "sha1": "d33ba2a34257b7ffb5a8c9c593704b177c7ef7be",
          "md5": "053aa962c1074510b3fb7d273f4409d1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.1.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit-2.1.21-sources.jar",
          "url": "kotlin-test-junit-2.1.21-sources.jar",
          "size": 2830,
          "sha512": "7e646d9971895dd20e122c2a51b0e062d0b03ef898e5886c17baa324ffdb651bf466b7169f828c3dd2f868145ae386f0520b0faa1b7017294742d07e4ebaa4b7",
          "sha256": "c411a0dad1218f3f652b6619f228fefee498903ee6e11c36c990fbc3fe823f18",
          "sha1": "48ca1b92544803c16b9042ae5b5976f6469e0a8c",
          "md5": "ff35307cfd380882a2b7a0d77f06e1b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.1.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.21"
        }
      ]
    }
  ]
}