{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.7/kotlin-logging-7.0.7.module",
    "group": "io.github.oshai",
    "module": "kotlin-logging",
    "version": "7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-iosArm64Main-7.0.7.klib",
          "url": "kotlin-logging-iosarm64-7.0.7.klib",
          "size": 51666,
          "sha512": "10704c5a681d21201dd7ff613ab952c65319f9a127303fbe9c66d3c47bca1ab8f9dfb95ce6ba0c248c830433b9016fba2b038f570d368b2c505adc9bccb500b3",
          "sha256": "884cd8523c647db854aaf583ed130093eb8b94598e59e04c9bd5d7ff6262405d",
          "sha1": "a8455dfb88ccda04ae2fdd2f593f7493bf51f786",
          "md5": "b5401cfceb6260ca7f2c1eea52724cd8"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-logging-iosarm64-7.0.7-sources.jar",
          "url": "kotlin-logging-iosarm64-7.0.7-sources.jar",
          "size": 16496,
          "sha512": "bd1dab8709b1a2d3cc798bf285bf936216e5ea5759f80e89e8af56bcf76e52d30352deaf335e0dc0fe8bb230482e02b022c7c872377418038668a3f372015996",
          "sha256": "4e273ad46eff6f1878a64f6b6ff98477709223dfecaa6d63fd3019fbb4da6162",
          "sha1": "2bfe758ad68d35ee3131001cd5dff984e52c890b",
          "md5": "50ce16cbbf7a625e8b862c29d87b3b79"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-iosarm64-7.0.7-metadata.jar",
          "url": "kotlin-logging-iosarm64-7.0.7-metadata.jar",
          "size": 9231,
          "sha512": "ae535e820eeff0adf45701a3570f15f74c47da80f7ef9be827bdceb343c1df0753eff77706ff6cf0fcc5662ad112e8604ef4c448d7e0a265aad4fd43b257546c",
          "sha256": "7840d0d0b1dc63eb1a15ff33a14deaa4097a5cfef32b66294148b92ab7d9f5af",
          "sha1": "7cd7878ae09531fc238ba0775b3511b4d9dc1e96",
          "md5": "66362ee0824de3e16aa23d5a4d5e907c"
        }
      ]
    }
  ]
}
