{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-datetime/0.6.2/kotlinx-datetime-0.6.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-datetime",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-datetime.klib",
          "url": "kotlinx-datetime-iossimulatorarm64-0.6.2.klib",
          "size": 537344,
          "sha512": "98c336d6583d048f1b20130357e8677a41510df329311d69838faa11227b1001b386e99f1f1c9ad921a7950042dee9e7af4b57d54d759eb178f54f40152a577b",
          "sha256": "9a88a116a71e2bf395578b485b4cac989a701c9283b4ccd8093ba505be17daff",
          "sha1": "f47d4eae08e49d82afcf57ef1bfd211abbe7762f",
          "md5": "ca50f2619fec4ddc128245eb077b4735"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-datetime-iossimulatorarm64-0.6.2-sources.jar",
          "url": "kotlinx-datetime-iossimulatorarm64-0.6.2-sources.jar",
          "size": 146461,
          "sha512": "deb0509ffe950ca7036213d30266b1a5a6acde4ade9833cda13a545dd874fa64afc2e8591f52ee68eb73e0dc569028ef3a0c017eedaa8203cabb58aecd64faaa",
          "sha256": "12d534888b72f6b3d999ca3fcea6a22f1a18520f1cc183b22d7ea8c83bdd0766",
          "sha1": "02a10305ed2d291f44633352920544d727fede2e",
          "md5": "3f7b209cbe9acaa0865eb1a5383f593f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-datetime-iossimulatorarm64-0.6.2-metadata.jar",
          "url": "kotlinx-datetime-iossimulatorarm64-0.6.2-metadata.jar",
          "size": 8060,
          "sha512": "b9d090c6a2a0093a48da22ea0b4b20eea97f4de13b259b90e342bcb26ad400de65c3adc3826b5d0f62170ff09a1d83f92cd4e9bc763af20ddad606f55766d29d",
          "sha256": "9c51cfee718c1d7301fca08953b3a9c7b8ace51dc8a232d504f0aa5b69098623",
          "sha1": "738ab0c5c3849b03d4fae875cd1363ba09429fd3",
          "md5": "d891387a1d0795dea87d1a6e02db0440"
        }
      ]
    }
  ]
}
