{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.26.1/atomicfu-0.26.1.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu.klib",
          "url": "atomicfu-iossimulatorarm64-0.26.1.klib",
          "size": 51240,
          "sha512": "9a920b2422da3766f61dd8582790b318f1feaca6ec4ce6c9e9e05f42979aaba96cb4d6a2a33f8cb6e875e633ee5211052980b841a495fd7e68dc335e8f61e359",
          "sha256": "6af88eac3e6c92569bdc7cd2eb9d4a6e9fd83e288ad21461386e6e40fc8644cc",
          "sha1": "f2606562d354599c0a885804b250ddfab70e02a2",
          "md5": "df414f53fa8bcad10fc55a89887aa26d"
        },
        {
          "name": "atomicfu-cinterop-interop.klib",
          "url": "atomicfu-iossimulatorarm64-0.26.1-cinterop-interop.klib",
          "size": 3821,
          "sha512": "07a8ebc425ce10ab9cb038f57eb2bda92e5e66a2594ed36b9b54621ff9951e97963ff7e5d03f77d74ef04957cd3428129b8afa6e6d416b83788d8edca81a19e9",
          "sha256": "97b7bbfb050b0a1618386d0de30ab35e144b0077d6eeb5dbdfe212c4d320e61f",
          "sha1": "6956fa7c75030aa13784fb0f3a062c4c8a674d0e",
          "md5": "49b678d6f4654a2a634950aceda6f680"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "atomicfu-iossimulatorarm64-0.26.1-sources.jar",
          "url": "atomicfu-iossimulatorarm64-0.26.1-sources.jar",
          "size": 12642,
          "sha512": "700d806d1bae74ef43ed26465e7e325b190b96e593c8460e3c8e947e23430bf611efc50d4f2ecd92c57ecd83786627d581bcf8362b9757d6cc2b4bc18a73a61a",
          "sha256": "7416a0b767b67e97b11a34ea3399b55c40a04300921e9ede73d45fee6ed61584",
          "sha1": "08781f11fd8f4d7b2e37a6816798648d478c5403",
          "md5": "bffb1e99fa46163f9c87ce84950348d7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-iossimulatorarm64-0.26.1-metadata.jar",
          "url": "atomicfu-iossimulatorarm64-0.26.1-metadata.jar",
          "size": 12585,
          "sha512": "7160d4c98862215ed0c38881f5cf38989197a1e0653ad420c08f145f5ed880c4a59c28a1e3bf2e5a8445bea937b0efaff89f6e9279b274ef138db5b2995fd600",
          "sha256": "2349a858d86e3b819081f7f6bb84fdc281f13c84fa8f2741daaba3c551978b46",
          "sha1": "05f046d821b6922bb180f06ec06b2a6f929294dd",
          "md5": "6681a5e4ca8c9503c60dc07ca7aaaac5"
        }
      ]
    }
  ]
}
