{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.23.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-metadata-0.23.1.jar",
          "url": "atomicfu-0.23.1.jar",
          "size": 21743,
          "sha512": "f802534f8efd9d346c3f56292189568e0ce8a62817714a5e2ceabf93314b0262051c328039704ef5af8ec35637687e517cd7926cd585bf671b0c339a6906fcc8",
          "sha256": "7db8660ebe4b91bb478edb3616c4e3a50ba59c07dca517d1e1284c03fe86ac57",
          "sha1": "c83617142902b4bd244ead7f53bbbf04d2289fc8",
          "md5": "c6d4ba885b708fc45b0cd89f8acfef50"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "atomicfu-kotlin-0.23.1-sources.jar",
          "url": "atomicfu-0.23.1-sources.jar",
          "size": 13634,
          "sha512": "b6e6c5d224ee9c675ad559a5a506b2286bf1f21e1987a1e1e2edb7e801e394d9260780eb14f2d089176a4ee5e5a6266db1873e5b5c97a65a8fd0fedbea1400ed",
          "sha256": "b0c3466c1834d2f0346f0968a2f213942fa825a6f6d5c482c4e1c069c444dddb",
          "sha1": "e99bff78d776fddc1565735021a320178cb3a322",
          "md5": "70d89311e8967fb62e9cc253151a902b"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm32/0.23.1/atomicfu-androidnativearm32-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm32",
        "version": "0.23.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm32/0.23.1/atomicfu-androidnativearm32-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm32",
        "version": "0.23.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm64/0.23.1/atomicfu-androidnativearm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm64/0.23.1/atomicfu-androidnativearm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex64/0.23.1/atomicfu-androidnativex64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex64",
        "version": "0.23.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex64/0.23.1/atomicfu-androidnativex64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex64",
        "version": "0.23.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex86/0.23.1/atomicfu-androidnativex86-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex86",
        "version": "0.23.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex86/0.23.1/atomicfu-androidnativex86-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex86",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.23.1/atomicfu-iosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.23.1/atomicfu-iosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.23.1/atomicfu-iosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.23.1/atomicfu-iossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.23.1/atomicfu-iossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.23.1/atomicfu-iossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.23.1/atomicfu-iosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.23.1/atomicfu-iosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.23.1/atomicfu-iosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.23.1/atomicfu-js-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.23.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.23.1/atomicfu-js-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.23.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.23.1/atomicfu-js-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.23.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.23.1/atomicfu-jvm-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.23.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.23.1/atomicfu-jvm-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.23.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.23.1/atomicfu-jvm-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.23.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxarm64/0.23.1/atomicfu-linuxarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxarm64/0.23.1/atomicfu-linuxarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxx64/0.23.1/atomicfu-linuxx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxx64/0.23.1/atomicfu-linuxx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.23.1/atomicfu-macosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.23.1/atomicfu-macosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.23.1/atomicfu-macosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.23.1/atomicfu-macosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.23.1/atomicfu-macosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.23.1/atomicfu-macosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-mingwx64/0.23.1/atomicfu-mingwx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-mingwx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-mingwx64/0.23.1/atomicfu-mingwx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-mingwx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.23.1/atomicfu-tvosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.23.1/atomicfu-tvosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.23.1/atomicfu-tvosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.23.1/atomicfu-tvossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.23.1/atomicfu-tvossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.23.1/atomicfu-tvossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.23.1/atomicfu-tvosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.23.1/atomicfu-tvosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.23.1/atomicfu-tvosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../atomicfu-wasm-js/0.23.1/atomicfu-wasm-js-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-wasm-js",
        "version": "0.23.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../atomicfu-wasm-js/0.23.1/atomicfu-wasm-js-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-wasm-js",
        "version": "0.23.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../atomicfu-wasm-js/0.23.1/atomicfu-wasm-js-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-wasm-js",
        "version": "0.23.1"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../atomicfu-wasm-wasi/0.23.1/atomicfu-wasm-wasi-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-wasm-wasi",
        "version": "0.23.1"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../atomicfu-wasm-wasi/0.23.1/atomicfu-wasm-wasi-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-wasm-wasi",
        "version": "0.23.1"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../atomicfu-wasm-wasi/0.23.1/atomicfu-wasm-wasi-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-wasm-wasi",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.23.1/atomicfu-watchosarm32-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.23.1/atomicfu-watchosarm32-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.23.1/atomicfu-watchosarm32-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.23.1/atomicfu-watchosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.23.1/atomicfu-watchosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.23.1/atomicfu-watchosarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosdevicearm64/0.23.1/atomicfu-watchosdevicearm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosdevicearm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosdevicearm64/0.23.1/atomicfu-watchosdevicearm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosdevicearm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosdevicearm64/0.23.1/atomicfu-watchosdevicearm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosdevicearm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.23.1/atomicfu-watchossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.23.1/atomicfu-watchossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.23.1/atomicfu-watchossimulatorarm64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.23.1/atomicfu-watchosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.23.1/atomicfu-watchosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.23.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.23.1/atomicfu-watchosx64-0.23.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.23.1"
      }
    }
  ]
}
