{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.7/kotlin-logging-7.0.7.module",
    "group": "io.github.oshai",
    "module": "kotlin-logging",
    "version": "7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-linuxX64Main-7.0.7.klib",
          "url": "kotlin-logging-linuxx64-7.0.7.klib",
          "size": 59329,
          "sha512": "7f7a0f110b5e92e2e68e52d3297312ebae3a58ddd75fde94923e2d02031fe38291f67acb9ba88c2fe8a3f83fc2d9d7a0205932385fc7f6711a72bd3f882c4e1a",
          "sha256": "c38be4d022332192d566eb8bb1c44e04556fc798a730561569e3c0ce8ee781a9",
          "sha1": "39fe060906f3b0038926c2f4ab3a237c8bdf02bc",
          "md5": "26ccb39efe126bf131e215916a04f9fb"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-logging-linuxx64-7.0.7-sources.jar",
          "url": "kotlin-logging-linuxx64-7.0.7-sources.jar",
          "size": 20201,
          "sha512": "4c7ca5e16cf801d9d315da093d1d9c7a43f5d3c0d68584610baaad205b061b26e145cff26aa717042f411a034c2a749ecdad993c78272520d23b8b94689a3cd9",
          "sha256": "e17789d3323197aace91091e0c2563797ab53750466f6ff50f592b21c75ee0ad",
          "sha1": "7ead86b2f539ec848cd1becb7e095295111d14a6",
          "md5": "a5039892c87f0d38983d3ea938daba09"
        }
      ]
    }
  ]
}
