{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.scottpierce",
    "module": "kotlin-env-var",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-env-var-metadata.jar",
          "url": "kotlin-env-var-1.0.5.jar",
          "size": 5268,
          "sha512": "4a9b771c0a67f79cdf0e3587d8a860d8a0e0cf1792ea0ef65b992accf454f718ea92b9967e55053fb7f2462c7d9707d756424aedffdcfc880cf5a7edc259e5f5",
          "sha256": "0904c2ffa1fbb4d09c790af589789d3c318415032ff8cfc6698cafe059bff7fe",
          "sha1": "14f9b8d95e4a060238c37d3d5d90c32a8e94199d",
          "md5": "0991e1353224056627a1a79a98f80c00"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-env-var-kotlin-sources.jar",
          "url": "kotlin-env-var-1.0.5-sources.jar",
          "size": 2492,
          "sha512": "3fc288d64cecd8f5e1cd2c8dd20138b0b0bd9fb08b2eff6fcd4f4d4270da34d87b1d31018779da1a38e29793bf4912d02b566d7910b3a6d78bbfbc1254a4ec78",
          "sha256": "7a33aea500b819b8ae58bd031b1756c748f1344ca3a6695d7ac7f74491e1dcaf",
          "sha1": "e7a855db548a1e513a05eafb4cd42fadb993cb8b",
          "md5": "27fdb07e8f03d3d412dfcc2920eb807b"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iosarm64/1.0.5/kotlin-env-var-iosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iosarm64/1.0.5/kotlin-env-var-iosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iosarm64/1.0.5/kotlin-env-var-iosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iossimulatorarm64/1.0.5/kotlin-env-var-iossimulatorarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iossimulatorarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iossimulatorarm64/1.0.5/kotlin-env-var-iossimulatorarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iossimulatorarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iossimulatorarm64/1.0.5/kotlin-env-var-iossimulatorarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iossimulatorarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iosx64/1.0.5/kotlin-env-var-iosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iosx64/1.0.5/kotlin-env-var-iosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-iosx64/1.0.5/kotlin-env-var-iosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-iosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-env-var-js/1.0.5/kotlin-env-var-js-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-env-var-js/1.0.5/kotlin-env-var-js-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-env-var-js/1.0.5/kotlin-env-var-js-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-env-var-jvm/1.0.5/kotlin-env-var-jvm-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-jvm",
        "version": "1.0.5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-env-var-jvm/1.0.5/kotlin-env-var-jvm-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-jvm",
        "version": "1.0.5"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-env-var-jvm/1.0.5/kotlin-env-var-jvm-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-jvm",
        "version": "1.0.5"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-linuxarm64/1.0.5/kotlin-env-var-linuxarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-linuxarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-linuxarm64/1.0.5/kotlin-env-var-linuxarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-linuxarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-linuxx64/1.0.5/kotlin-env-var-linuxx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-linuxx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-linuxx64/1.0.5/kotlin-env-var-linuxx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-linuxx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-macosarm64/1.0.5/kotlin-env-var-macosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-macosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-macosarm64/1.0.5/kotlin-env-var-macosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-macosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-macosarm64/1.0.5/kotlin-env-var-macosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-macosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-macosx64/1.0.5/kotlin-env-var-macosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-macosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-macosx64/1.0.5/kotlin-env-var-macosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-macosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-macosx64/1.0.5/kotlin-env-var-macosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-macosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-mingwx64/1.0.5/kotlin-env-var-mingwx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-mingwx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-mingwx64/1.0.5/kotlin-env-var-mingwx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-mingwx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvosarm64/1.0.5/kotlin-env-var-tvosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvosarm64/1.0.5/kotlin-env-var-tvosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvosarm64/1.0.5/kotlin-env-var-tvosarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvosarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvossimulatorarm64/1.0.5/kotlin-env-var-tvossimulatorarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvossimulatorarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvossimulatorarm64/1.0.5/kotlin-env-var-tvossimulatorarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvossimulatorarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvossimulatorarm64/1.0.5/kotlin-env-var-tvossimulatorarm64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvossimulatorarm64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvosx64/1.0.5/kotlin-env-var-tvosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvosx64/1.0.5/kotlin-env-var-tvosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-env-var-tvosx64/1.0.5/kotlin-env-var-tvosx64-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-tvosx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-env-var-wasm-js/1.0.5/kotlin-env-var-wasm-js-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-wasm-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-env-var-wasm-js/1.0.5/kotlin-env-var-wasm-js-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-wasm-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-env-var-wasm-js/1.0.5/kotlin-env-var-wasm-js-1.0.5.module",
        "group": "dev.scottpierce",
        "module": "kotlin-env-var-wasm-js",
        "version": "1.0.5"
      }
    }
  ]
}
