{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vanniktech",
    "module": "nexus",
    "version": "0.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "nexus-0.29.0.jar",
          "url": "nexus-0.29.0.jar",
          "size": 73485,
          "sha512": "a9b6d8e825e95e8be18ad36bad11b887184cc85807f03e5f3e6ff96419b9d1934f006feb9a79568e7097bb4e6312798cad55ce9d88c75f76eb984b6791ecc1e6",
          "sha256": "bb0333bca37a4048c03fc4ec2e191fb8dd57e616159ac0bf20c87de5793dc30b",
          "sha1": "8c615bed778597b845e310e31641d6a7284966c9",
          "md5": "2c07ebe433e14e7fedf8757f4a345ca1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "nexus-0.29.0.jar",
          "url": "nexus-0.29.0.jar",
          "size": 73485,
          "sha512": "a9b6d8e825e95e8be18ad36bad11b887184cc85807f03e5f3e6ff96419b9d1934f006feb9a79568e7097bb4e6312798cad55ce9d88c75f76eb984b6791ecc1e6",
          "sha256": "bb0333bca37a4048c03fc4ec2e191fb8dd57e616159ac0bf20c87de5793dc30b",
          "sha1": "8c615bed778597b845e310e31641d6a7284966c9",
          "md5": "2c07ebe433e14e7fedf8757f4a345ca1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nexus-0.29.0-sources.jar",
          "url": "nexus-0.29.0-sources.jar",
          "size": 5222,
          "sha512": "a4bea703016a0abfcb2687d5fb9e469376373e9c16c9135d4a50eaef7a6592a0cc9c16ffae3ba48501241714d02993756b2c6117e26a4c335e83e41ce7bd4b07",
          "sha256": "8604e165ee4415a54e5f39a99382683cb0b067bcf3af86d876f601520cf3edad",
          "sha1": "48dc9d941c85dfb00295834b5f3f8f746e65abc9",
          "md5": "c6bb8563da258f03e08eb86eed73f961"
        }
      ]
    }
  ]
}
