{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.10.2/kotlinx-coroutines-core-1.10.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-linuxX64Main-1.10.2.klib",
          "url": "kotlinx-coroutines-core-linuxx64-1.10.2.klib",
          "size": 883555,
          "sha512": "edaba97985dc60996c029f426184f60f56454c1d2a2a959cfc23c13d137a27acf8bd68a215d6204f6085d685e52379717189f01d75bf52913c45a5777c649262",
          "sha256": "de4bfd5a112889183f37717b026bdfafc332552cd376584a88d2f3c9aaed6b3e",
          "sha1": "874eb5230e06255467751c266fdcb8e0abcd0922",
          "md5": "eb74ecda0690b5d74b0389356e224646"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-linuxx64-1.10.2-sources.jar",
          "url": "kotlinx-coroutines-core-linuxx64-1.10.2-sources.jar",
          "size": 327660,
          "sha512": "36d6e8a2f5e24e7d698805c7016c16b049c6086bef84c21b9775027ba9a5fed20412ba336ef95427cdab00003ad945f7811f268a41271c0fb2a7751c94bea5e8",
          "sha256": "f89dd00f832d0ab0f89c855224324336035e463fa518909cdf6c9a8da43823e6",
          "sha1": "2a1bbcf78194dcc76463bdfa19994485c49e382c",
          "md5": "3cf2a0bb838854e8ca683f9ddf5a7352"
        }
      ]
    }
  ]
}
