{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-fakefilesystem/3.11.0/okio-fakefilesystem-3.11.0.module",
    "group": "com.squareup.okio",
    "module": "okio-fakefilesystem",
    "version": "3.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-fakefilesystem-linuxX64Main-3.11.0.klib",
          "url": "okio-fakefilesystem-linuxx64-3.11.0.klib",
          "size": 41458,
          "sha512": "180ba8b53abf57433a0a83a433fe1a896ed320a94d72d7e79c46ac4a1a1b516fa1c00972195b0222be7eca893531bafd5966207e8eaedf8306cf07d6b4625fa7",
          "sha256": "b5289dda446ebc848270d0900a62a7d3c6aea3277e5ddc4778f82c194cc0b988",
          "sha1": "5d1d814008d5eb6132c71d027a8e616703a657d0",
          "md5": "faeb04265c4f3b212790aa2ac08b632c"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "okio-fakefilesystem-linuxx64-3.11.0-sources.jar",
          "url": "okio-fakefilesystem-linuxx64-3.11.0-sources.jar",
          "size": 8413,
          "sha512": "cb4fb94a52c905aaa9ad083dae916532bca1d90e410a736c8cd0dfcf277a4508bb05c4f790a844e8f937c18d19853c4dc7adb967e18cb0d3ff97756bd84f41a5",
          "sha256": "72b36ee3c7267a6cd7373d639a3ae680f2cca2e1f93b23562f437941e6acfa94",
          "sha1": "25aaa8508f23399f7ee242c6c2a9be1ec32711a5",
          "md5": "81cea84046945f3088b910c115edef1e"
        }
      ]
    }
  ]
}
