{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bignum/0.3.10/bignum-0.3.10.module",
    "group": "com.ionspin.kotlin",
    "module": "bignum",
    "version": "0.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "bignum.klib",
          "url": "bignum-iosarm64-0.3.10.klib",
          "size": 440193,
          "sha512": "83e2b8f4916e3b4d089278630f729cd4cfe4b889e595eb0c22f3eae836ce844ec479fc8011445206f2908be7c2a553c2988d1d2eb29e4e22b7752d6890e11864",
          "sha256": "a745b1e4adc85c1d036f897a6b2db24e9bc70186f2551cba95a11b30a25eb70a",
          "sha1": "572680271793b3c3644a099ccf2876c862e97f1c",
          "md5": "b6a562f40bc13020d7e06cfa3fdc28f2"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "bignum-iosarm64-0.3.10-sources.jar",
          "url": "bignum-iosarm64-0.3.10-sources.jar",
          "size": 90858,
          "sha512": "e1b7b37d25212e7c6cb48640ff38c3fa71c3dedcc425ab8fbbc3e9128d8ccd8efc24d8379da083516267fd7dfcb8e11e001a87cff4657318b3eee7701a43782e",
          "sha256": "43282ee1aaef090aa2721c8cbabef2c4281afb60ff0df481a5ad509ce9ca6630",
          "sha1": "39f081a4a13bff8a7f65b8735b600e83a027c651",
          "md5": "59ee189ee079613da30d9a5e46f064aa"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "bignum-iosarm64-0.3.10-metadata.jar",
          "url": "bignum-iosarm64-0.3.10-metadata.jar",
          "size": 2854,
          "sha512": "d27e42f3f7de4b0bcebb605082b8b1792b1d32d7bf947aff6f680e9a8728d9a812da06ae93e622a1ccbb960bd2e0a600ffd11124368d90041c6ce21c9a3ea201",
          "sha256": "e505dc5fde88c6d8938b46fc7b65c9aba3e1d249b7cf9b302b11e797cdf0f56e",
          "sha1": "09f7126b150a08340ae161989ce5049a26dbdfe9",
          "md5": "d0b46b14746318dcb777f3936bf5f44f"
        }
      ]
    }
  ]
}
