{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vanniktech",
    "module": "gradle-maven-publish-plugin",
    "version": "0.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-maven-publish-plugin-0.29.0.jar",
          "url": "gradle-maven-publish-plugin-0.29.0.jar",
          "size": 113604,
          "sha512": "5f8bce0243db269237f246df2e10b6f3611187ae8d26a4330e66dfb09cc2a15acbc628fd42941fd4b42f831870336eb1aa771d966123a6f78e45480979932659",
          "sha256": "fa7cb6fff55e26f2ddcea968a9d89fc52a57e7e7435d6ac1493d364fc7c6f9e8",
          "sha1": "bda1e07de8774559d55f0653e968f227e85a9848",
          "md5": "7731c42505f8539e9dd61d7954c5320e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vanniktech",
          "module": "central-portal",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "nexus",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-maven-publish-plugin-0.29.0.jar",
          "url": "gradle-maven-publish-plugin-0.29.0.jar",
          "size": 113604,
          "sha512": "5f8bce0243db269237f246df2e10b6f3611187ae8d26a4330e66dfb09cc2a15acbc628fd42941fd4b42f831870336eb1aa771d966123a6f78e45480979932659",
          "sha256": "fa7cb6fff55e26f2ddcea968a9d89fc52a57e7e7435d6ac1493d364fc7c6f9e8",
          "sha1": "bda1e07de8774559d55f0653e968f227e85a9848",
          "md5": "7731c42505f8539e9dd61d7954c5320e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-maven-publish-plugin-0.29.0-sources.jar",
          "url": "gradle-maven-publish-plugin-0.29.0-sources.jar",
          "size": 20583,
          "sha512": "5820a95bfbffce70384bc8d40f9136f34a5c026121aebefae15158a4027f68dfdf8400f161aa234336078ecb1b98ea51adee98cb21362efb887107b467241268",
          "sha256": "bf1f97f3259a221da7b28d6310079ae2f7830d1b9c0c6f8d2726951b46bd5569",
          "sha1": "e3a98ee984da262df48ab172bf867c4101f8c9ab",
          "md5": "1b26749267faac699f12d68454583fc2"
        }
      ]
    }
  ]
}
