{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.7/kotlin-logging-7.0.7.module",
    "group": "io.github.oshai",
    "module": "kotlin-logging",
    "version": "7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-iosSimulatorArm64Main-7.0.7.klib",
          "url": "kotlin-logging-iossimulatorarm64-7.0.7.klib",
          "size": 51751,
          "sha512": "501c72ba41af20048e6a437ae236cabb4cea2b1ef0625253b19a336806f5cc8bb65606276527011be874f399e9c55c168b627aa286f2c0f3ae4ccc8b530b843e",
          "sha256": "ca3392783bd683f2f07be36c3f882f12f9b76b06960840e3e4484d2a36b17fcf",
          "sha1": "2661d5f1709772522b5b3896662edea6f19032ec",
          "md5": "9908479b70843a84dd5767f57a969532"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-logging-iossimulatorarm64-7.0.7-sources.jar",
          "url": "kotlin-logging-iossimulatorarm64-7.0.7-sources.jar",
          "size": 16496,
          "sha512": "bd1dab8709b1a2d3cc798bf285bf936216e5ea5759f80e89e8af56bcf76e52d30352deaf335e0dc0fe8bb230482e02b022c7c872377418038668a3f372015996",
          "sha256": "4e273ad46eff6f1878a64f6b6ff98477709223dfecaa6d63fd3019fbb4da6162",
          "sha1": "2bfe758ad68d35ee3131001cd5dff984e52c890b",
          "md5": "50ce16cbbf7a625e8b862c29d87b3b79"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-iossimulatorarm64-7.0.7-metadata.jar",
          "url": "kotlin-logging-iossimulatorarm64-7.0.7-metadata.jar",
          "size": 9231,
          "sha512": "ae535e820eeff0adf45701a3570f15f74c47da80f7ef9be827bdceb343c1df0753eff77706ff6cf0fcc5662ad112e8604ef4c448d7e0a265aad4fd43b257546c",
          "sha256": "7840d0d0b1dc63eb1a15ff33a14deaa4097a5cfef32b66294148b92ab7d9f5af",
          "sha1": "7cd7878ae09531fc238ba0775b3511b4d9dc1e96",
          "md5": "66362ee0824de3e16aa23d5a4d5e907c"
        }
      ]
    }
  ]
}
