{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ionspin.kotlin",
    "module": "bignum",
    "version": "0.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "bignum-metadata-0.3.10.jar",
          "url": "bignum-0.3.10.jar",
          "size": 34512,
          "sha512": "8fa5c6fc0c15a4860b60a49aa92d92cb275f5354ecb4297bce3c2b09bd1211362e6c152cb96556c6e486790e48d6fee7eb16b5bb9b10c60b67ecab5b89b36565",
          "sha256": "9183f3da7a4944ca41ef9f79f51a6a178cbc021936de44e6e9265c6f040eb45c",
          "sha1": "32b144fb92fae4aaeb49b65875d593b16ad73393",
          "md5": "1c9c4a5e3bab7f4488f796d820ba7650"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "bignum-kotlin-0.3.10-sources.jar",
          "url": "bignum-0.3.10-sources.jar",
          "size": 91824,
          "sha512": "d7082921d7b15c199afb7ee0181e270a6d06070f38dd6c1974910cde7ac34771314b4398c56b2724db58245a0ab608a90e1fd583899ab82eb4a857e569307ff0",
          "sha256": "43035167d250b3eb26ae118e347fa8df1a2de37c7255b94f94a56472e0e75877",
          "sha1": "3bcf295b00433c02f1fb33c682fc0c8eb78624a8",
          "md5": "3b4f306bd58ebd3dc1d5e927d7495a0b"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativearm32/0.3.10/bignum-androidnativearm32-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativearm32",
        "version": "0.3.10"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativearm32/0.3.10/bignum-androidnativearm32-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativearm32",
        "version": "0.3.10"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativearm64/0.3.10/bignum-androidnativearm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativearm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativearm64/0.3.10/bignum-androidnativearm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativearm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativex64/0.3.10/bignum-androidnativex64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativex64",
        "version": "0.3.10"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativex64/0.3.10/bignum-androidnativex64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativex64",
        "version": "0.3.10"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativex86/0.3.10/bignum-androidnativex86-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativex86",
        "version": "0.3.10"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-androidnativex86/0.3.10/bignum-androidnativex86-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-androidnativex86",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iosarm64/0.3.10/bignum-iosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iosarm64/0.3.10/bignum-iosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iosarm64/0.3.10/bignum-iosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iossimulatorarm64/0.3.10/bignum-iossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iossimulatorarm64/0.3.10/bignum-iossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iossimulatorarm64/0.3.10/bignum-iossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iosx64/0.3.10/bignum-iosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iosx64/0.3.10/bignum-iosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-iosx64/0.3.10/bignum-iosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-iosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bignum-js/0.3.10/bignum-js-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-js",
        "version": "0.3.10"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bignum-js/0.3.10/bignum-js-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-js",
        "version": "0.3.10"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bignum-js/0.3.10/bignum-js-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-js",
        "version": "0.3.10"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bignum-jvm/0.3.10/bignum-jvm-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-jvm",
        "version": "0.3.10"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bignum-jvm/0.3.10/bignum-jvm-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-jvm",
        "version": "0.3.10"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bignum-jvm/0.3.10/bignum-jvm-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-jvm",
        "version": "0.3.10"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-linuxarm64/0.3.10/bignum-linuxarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-linuxarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-linuxarm64/0.3.10/bignum-linuxarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-linuxarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-linuxx64/0.3.10/bignum-linuxx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-linuxx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-linuxx64/0.3.10/bignum-linuxx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-linuxx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-macosarm64/0.3.10/bignum-macosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-macosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-macosarm64/0.3.10/bignum-macosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-macosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-macosarm64/0.3.10/bignum-macosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-macosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-macosx64/0.3.10/bignum-macosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-macosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-macosx64/0.3.10/bignum-macosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-macosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-macosx64/0.3.10/bignum-macosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-macosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-mingwx64/0.3.10/bignum-mingwx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-mingwx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-mingwx64/0.3.10/bignum-mingwx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-mingwx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvosarm64/0.3.10/bignum-tvosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvosarm64/0.3.10/bignum-tvosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvosarm64/0.3.10/bignum-tvosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvossimulatorarm64/0.3.10/bignum-tvossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvossimulatorarm64/0.3.10/bignum-tvossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvossimulatorarm64/0.3.10/bignum-tvossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvosx64/0.3.10/bignum-tvosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvosx64/0.3.10/bignum-tvosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-tvosx64/0.3.10/bignum-tvosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-tvosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../bignum-wasm-js/0.3.10/bignum-wasm-js-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-wasm-js",
        "version": "0.3.10"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../bignum-wasm-js/0.3.10/bignum-wasm-js-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-wasm-js",
        "version": "0.3.10"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../bignum-wasm-js/0.3.10/bignum-wasm-js-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-wasm-js",
        "version": "0.3.10"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../bignum-wasm-wasi/0.3.10/bignum-wasm-wasi-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-wasm-wasi",
        "version": "0.3.10"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../bignum-wasm-wasi/0.3.10/bignum-wasm-wasi-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-wasm-wasi",
        "version": "0.3.10"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../bignum-wasm-wasi/0.3.10/bignum-wasm-wasi-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-wasm-wasi",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosarm32/0.3.10/bignum-watchosarm32-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosarm32",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosarm32/0.3.10/bignum-watchosarm32-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosarm32",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosarm32/0.3.10/bignum-watchosarm32-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosarm32",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosarm64/0.3.10/bignum-watchosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosarm64/0.3.10/bignum-watchosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosarm64/0.3.10/bignum-watchosarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosdevicearm64/0.3.10/bignum-watchosdevicearm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosdevicearm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosdevicearm64/0.3.10/bignum-watchosdevicearm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosdevicearm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosdevicearm64/0.3.10/bignum-watchosdevicearm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosdevicearm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchossimulatorarm64/0.3.10/bignum-watchossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchossimulatorarm64/0.3.10/bignum-watchossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchossimulatorarm64/0.3.10/bignum-watchossimulatorarm64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchossimulatorarm64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosx64/0.3.10/bignum-watchosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosx64/0.3.10/bignum-watchosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosx64",
        "version": "0.3.10"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bignum-watchosx64/0.3.10/bignum-watchosx64-0.3.10.module",
        "group": "com.ionspin.kotlin",
        "module": "bignum-watchosx64",
        "version": "0.3.10"
      }
    }
  ]
}
