{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "fus-statistics-gradle-plugin",
    "version": "2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-sources.jar",
          "size": 14137,
          "sha512": "26934375064fb6d1ff225fa138f144c7f7a93c0fcdc18ae9dd5841fbcd5777868ecb0213939721a00cc5f385d7061aaefc6fd01f76d2cc75c3c8ee3e31e21b17",
          "sha256": "13da02633df6ab93754c49459b282fd8f3a2c44c0e8f5f3d32432ee3b9248453",
          "sha1": "64eb311f64fb2b1dd5884019b24151060a4ff2da",
          "md5": "8e2e8ec6ff4c2f23d23ab519578468bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ]
    },
    {
      "name": "gradle80JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle80-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle80-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle80-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle80-sources.jar",
          "size": 14137,
          "sha512": "26934375064fb6d1ff225fa138f144c7f7a93c0fcdc18ae9dd5841fbcd5777868ecb0213939721a00cc5f385d7061aaefc6fd01f76d2cc75c3c8ee3e31e21b17",
          "sha256": "13da02633df6ab93754c49459b282fd8f3a2c44c0e8f5f3d32432ee3b9248453",
          "sha1": "64eb311f64fb2b1dd5884019b24151060a4ff2da",
          "md5": "8e2e8ec6ff4c2f23d23ab519578468bf"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle80.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle80.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle81JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle81-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle81-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle81-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle81-sources.jar",
          "size": 14137,
          "sha512": "26934375064fb6d1ff225fa138f144c7f7a93c0fcdc18ae9dd5841fbcd5777868ecb0213939721a00cc5f385d7061aaefc6fd01f76d2cc75c3c8ee3e31e21b17",
          "sha256": "13da02633df6ab93754c49459b282fd8f3a2c44c0e8f5f3d32432ee3b9248453",
          "sha1": "64eb311f64fb2b1dd5884019b24151060a4ff2da",
          "md5": "8e2e8ec6ff4c2f23d23ab519578468bf"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle81.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle81.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle82JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle82-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle82-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle82-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle82-sources.jar",
          "size": 14137,
          "sha512": "26934375064fb6d1ff225fa138f144c7f7a93c0fcdc18ae9dd5841fbcd5777868ecb0213939721a00cc5f385d7061aaefc6fd01f76d2cc75c3c8ee3e31e21b17",
          "sha256": "13da02633df6ab93754c49459b282fd8f3a2c44c0e8f5f3d32432ee3b9248453",
          "sha1": "64eb311f64fb2b1dd5884019b24151060a4ff2da",
          "md5": "8e2e8ec6ff4c2f23d23ab519578468bf"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle82.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle82.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle85JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle85-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle85-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle85-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle85-sources.jar",
          "size": 14137,
          "sha512": "26934375064fb6d1ff225fa138f144c7f7a93c0fcdc18ae9dd5841fbcd5777868ecb0213939721a00cc5f385d7061aaefc6fd01f76d2cc75c3c8ee3e31e21b17",
          "sha256": "13da02633df6ab93754c49459b282fd8f3a2c44c0e8f5f3d32432ee3b9248453",
          "sha1": "64eb311f64fb2b1dd5884019b24151060a4ff2da",
          "md5": "8e2e8ec6ff4c2f23d23ab519578468bf"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle85.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.21-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.1.21-gradle85.jar",
          "size": 77406,
          "sha512": "02712dcec593c326993d3120a46a97ecaa38a5585ff3b3137e1d31c3717f68857f9a4dfb394b42eaa61179b8aeb999e2254b8c6880484b2df9e803bb38c1e99a",
          "sha256": "fc0905810309a5ad3ea15dfbbe129a47e90db11215232364841b72044124e7b0",
          "sha1": "9e3cd70f790b81215e8d46c7a7b692090d10d833",
          "md5": "116a7b4aaf9af201da212e4f548788df"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.21"
        }
      ]
    }
  ]
}
