{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.2/kotlinx-serialization-core-1.6.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-iosarm64-1.6.2.klib",
          "size": 305960,
          "sha512": "01bca536297f4848d45ea9b4d12ec93f29b2be2b87ed29e229eb73c340389e3f69168f4326d22340d22b2883a7e8acae586faff81e74c03c576c9d1b4b03753d",
          "sha256": "d75688f576728f271df4b900692978a62d3db07d7cc833a891766ff6e1324e62",
          "sha1": "2bc7d39316b39a69a6f4bfe574c76c0e367eaf19",
          "md5": "dc78d2534bf66cc1eb40814a12f99b45"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-iosarm64-1.6.2-sources.jar",
          "url": "kotlinx-serialization-core-iosarm64-1.6.2-sources.jar",
          "size": 98857,
          "sha512": "163610cc58e56be22e56b67fb0e0c535bcdd3dde4f0cd6473749e44e3289e77e18ab6292bf29d514092a2b9c44f5105b03fc0dc4c32dfc1bb5e31f30a241f05f",
          "sha256": "3e4d8b02762c2c4843cdd45c201ec15b185e2782b52725084b1a5af308c95a0e",
          "sha1": "8e0e1f18ea762eae25a212bad83d20a3b7ae7035",
          "md5": "131fdce0948b4b0a66ea3dfc883b695e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-iosarm64-1.6.2-metadata.jar",
          "url": "kotlinx-serialization-core-iosarm64-1.6.2-metadata.jar",
          "size": 261,
          "sha512": "b7ffcb13a7752eeaaef926ca48a81d532670ba309056288a07fe1e3476ee36e27e725118f733f4961d1e40255f787d35599f44b122a0388fd9ca22032bf81482",
          "sha256": "6ded067663779f83b813ed8a8742e1132aa82ede699709450519346955af9420",
          "sha1": "c2171f605898e5256530af436fd652ce85bbe12c",
          "md5": "8b40809965acb6fdac3a1dd13edf0224"
        }
      ]
    }
  ]
}
